### ISSUE TITLE
Large test artefacts

### ISSUE THREAD

**Issue by k-wall** [maestro-performance/maestro-java#106]
When testing messaging components capable of very large throughputs (such as the Qpid Dispatch Router with ```anycast``` addresses), the volume of data generated by Maestro can be problematic both in terms of the length of time taken from the Maestro Client to download the artefact from the Worker and the disk utilisation.  Both hamper the desire for automated timely performance tests.

For instance a 2 minute test with one sender and receiver generated CSV (compressed) totalling almost 1GB.   If you are performing a scale test where you run successive tests ramping up workers, you can quickly generate an unmanageable quantities of data.  

One possible change would be to switch from the textual CSV format to a binary one.  This would reduce the size of each record to about 25%.

**Comment by orpiske** [comment]
Indeed, that's something that we need to address. Having these large files made the implementation of downloading the files via broker much more complicated as I have to break then in pieces due to limitations in the max frame size used by the brokers as well as the max payload size for MQTT itself (256Mb). 

One of my colleagues here mentioned an idea of a file format for Maestro and I'll reach out to him. I am certainly open to suggestions about other possible formats as well. 

As more testing scenarios and SUTs needs to be tested and the lab I have for daily work is not getting bigger reducing the post-processing time for the tests is critical. I think this is one of the problems that must be addressed in 1.4.

**Comment by orpiske** [comment]
Implemented on 1.4: the file format was changed to grow only in relation to time instead of both time and rate. Now, a full day of testing consumes 1.7 Mb on the rate file (without compression). I/O load on the worker servers also decreased w/ the new file file format.
The inspector still uses the CSV based format, but its files are much much smaller. Eventually, it will be converted to the new format as well. 
Closing the issue.
