### ISSUE TITLE
Maestro Client hangs

### ISSUE THREAD

**Issue by orpiske** [maestro-performance/maestro-java#99]
Another one reported by @k-wall on a scenario with high load.

> "main" #1 prio=5 os_prio=0 tid=0x00007f352800abe0 nid=0xc in Object.wait() [0x00007f35305e3000]
> 	   java.lang.Thread.State: WAITING (on object monitor)
> 		at java.lang.Object.wait(Native Method)
> 		at java.lang.Object.wait(Object.java:502)
> 		at org.eclipse.paho.client.mqttv3.internal.Token.waitUntilSent(Token.java:248)
> 		- locked <0x00000000d71dac88> (a java.lang.Object)
>     	at org.eclipse.paho.client.mqttv3.MqttTopic.publish(MqttTopic.java:117)
> 		at org.eclipse.paho.client.mqttv3.MqttTopic.publish(MqttTopic.java:97)
> 		at org.maestro.client.exchange.MaestroMqttClient.publish(MaestroMqttClient.java:135)
> 		at org.maestro.client.exchange.MaestroMqttClient.publish(MaestroMqttClient.java:196)
> 		at org.maestro.client.Maestro.stopReceiver(Maestro.java:408)
> 		at org.maestro.tests.AbstractTestExecutor.stopServices(AbstractTestExecutor.java:85)
> 		at org.maestro.tests.rate.FixedRateTestExecutor.runTest(FixedRateTestExecutor.java:255)
> 		at org.maestro.tests.rate.FixedRateTestExecutor.run(FixedRateTestExecutor.java:330)
> 		at org.maestro.tests.TestExecutor$run.call(Unknown Source)
> 		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
> 		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
> 		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
> 		at singlepoint.FixedRateTest.run(FixedRateTest.groovy:101)
> 		at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
> 		at groovy.lang.GroovyShell.run(GroovyShell.java:228)
> 		at org.maestro.cli.main.actions.exec.GroovyWrapper.run(GroovyWrapper.java:29)
> 		at org.maestro.cli.main.actions.ExecAction.run(ExecAction.java:83)
> 		at org.maestro.cli.main.Main.main(Main.java:114)

Somehow I think it's related to this known Paho Java issue: https://github.com/eclipse/paho.mqtt.java/issues/330. I'll have to investigate more.

**Comment by k-wall** [comment]
In this case the test scenario was 25 senders and 25 receivers (separate workers) distributed over a openshift cluster.   We had been successfully testing scenarios of 200 senders/200 receivers, so I don't think the problem relates to the number of workers.

The configuration of the system under test (EnMasse) had just been changed so that the number of messages processed would have been much higher on previous testing rounds.    My theory is that it is something to do with the size of the artefacts downloaded by the Maestro Client this is causing the issue.   Perhaps the tieing up of the MQTT worker threads for an extended period of time downloading the large CSVs triggers the issue?  This is just speculation on my behalf.

I saw the same issue appears 3 or 4 times in a row with the larger message volumes.

**Comment by k-wall** [comment]
I made an experimental change to use a thread pool to download files from the workers.  I have only tested this change with the ```DefaultDownloader```.   With this change I did not see a repeat of the problem I described above.

https://github.com/maestro-performance/maestro-java/pull/100
